/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medico.gui;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import medico.bean.Paciente;
import medico.dao.PacienteDao;
import medico.util.Utils;
import static medico.util.Utils.validaCpf;
import medico.util.guis;


/**
 *
 * @author celso
 */
public class FrmPacientes extends javax.swing.JInternalFrame {

    private Boolean NovoPaciente = true;
    private Paciente PacSelecionado;

    /**
     * Creates new form FrmPacientes
     */
    public FrmPacientes() {
        initComponents();
    }

    FrmResultBusca frb = new FrmResultBusca();
    FrmListagem flist = new FrmListagem();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMat = new clinica.util.JTextUpper();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new clinica.util.JTextUpper();
        jLabel1 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txtRg = new clinica.util.JTextUpper();
        jLabel6 = new javax.swing.JLabel();
        cmbDeclara = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtNasc = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTelRes = new clinica.util.JTextUpper();
        txtTelCom = new clinica.util.JTextUpper();
        txtTelCel = new clinica.util.JTextUpper();
        txtTelFax = new clinica.util.JTextUpper();
        txtTelOutro = new clinica.util.JTextUpper();
        txtOp1 = new clinica.util.JTextUpper();
        txtOp2 = new clinica.util.JTextUpper();
        jLabel13 = new javax.swing.JLabel();
        txtEmail = new clinica.util.JTextUpper();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtEnd = new clinica.util.JTextUpper();
        txtComp = new clinica.util.JTextUpper();
        txtBairro = new clinica.util.JTextUpper();
        txtCidade = new clinica.util.JTextUpper();
        txtUf = new clinica.util.JTextUpper();
        txtCep = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        lblLastVisita = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();
        lblErrorCpf = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtMatCli = new clinica.util.JTextUpper();
        jLabel28 = new javax.swing.JLabel();
        lbldtCadastro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCT = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCP = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtLF = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtCS = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtPA = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtUSG = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtRX = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtMGF = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtDO = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtOutrasObs = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnListagem = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtPesquisa = new clinica.util.JTextUpper();
        btnPesquisa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Controle de Pacientes");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do paciente"));

        jLabel3.setText("Número:");

        txtMat.setEditable(false);
        txtMat.setToolTipText("Número da Matrícula Médico");
        txtMat.setFocusable(false);
        txtMat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setText("Nome");

        txtNome.setToolTipText("Informe o nome do paciente");
        txtNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel1.setText("CPF");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setToolTipText("Informe o CPF do paciente");
        txtCpf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });

        jLabel5.setText("RG");

        txtRg.setToolTipText("Informe o RG do paciente");
        txtRg.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setText("Declara");

        cmbDeclara.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ND", "D" }));
        cmbDeclara.setToolTipText("Selecione se o paciente e declarante ou não");

        jLabel7.setText("Nascimento");

        try {
            txtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNasc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNasc.setToolTipText("Informe a data de nascimento do paciente");
        txtNasc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNascFocusLost(evt);
            }
        });
        txtNasc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNascKeyPressed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefones"));

        jLabel8.setText("Residêncial:");

        jLabel9.setText("Comercial:");

        jLabel12.setText("Outro:");

        txtTelRes.setToolTipText("Informe o telefone residêncial do paciente");
        txtTelRes.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTelCom.setToolTipText("Informe o telefone comercial do paciente");
        txtTelCom.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTelCel.setToolTipText("Informe o telefone celular do paciente");
        txtTelCel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTelFax.setToolTipText("Informe o telefone do fax do paciente");
        txtTelFax.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtTelOutro.setToolTipText("Informe algum outro telefone do paciente");
        txtTelOutro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtOp1.setToolTipText("Informe o telefone celular do paciente");
        txtOp1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtOp2.setToolTipText("Informe o telefone celular do paciente");
        txtOp2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel12)
                        .addComponent(txtOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtOp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelOutro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtTelCel, txtTelCom, txtTelFax, txtTelOutro, txtTelRes});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTelRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTelCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTelOutro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("E-Mail");

        txtEmail.setToolTipText("Informe o e-mail do paciente");
        txtEmail.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel14.setText("CEP");

        jLabel15.setText("Endereço");

        jLabel16.setText("Complemento");

        jLabel17.setText("Bairro");

        jLabel18.setText("Cidade");

        jLabel19.setText("UF");

        txtEnd.setToolTipText("Informe o endereço do paciente");
        txtEnd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtComp.setToolTipText("Informe o complemento para o endereço do paciente");
        txtComp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtBairro.setToolTipText("Informe o bairro do endereço do paciente");
        txtBairro.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtCidade.setToolTipText("Informe a cidade do paciente");
        txtCidade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        txtUf.setToolTipText("Informe a UF do endereço do paciente");
        txtUf.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setToolTipText("Informe o CEP do endereço do paciente");
        txtCep.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Observação"));

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        txtObs.setToolTipText("Informe alguma observação referênte ao paciente");
        txtObs.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtObs);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jLabel20.setText("Sexo");

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FEMININO", "MASCULINO" }));
        cmbSexo.setToolTipText("Selecione o sexo do paciente");

        jLabel26.setText("Data da última visita");

        jLabel27.setText("Idade");

        jLabel29.setText("Matrícula:");

        txtMatCli.setToolTipText("Número da matrícula na clínica");
        txtMatCli.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel28.setText("Data do Cadastro:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel27)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(lblErrorCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtCep)
                                    .addComponent(txtBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel18))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel19)
                                                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel16)
                                        .addComponent(cmbSexo, 0, 150, Short.MAX_VALUE))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lbldtCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbDeclara, javax.swing.GroupLayout.Alignment.LEADING, 0, 158, Short.MAX_VALUE)
                                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblLastVisita, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatCli, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(213, 213, 213))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldtCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(txtMatCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDeclara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel13)
                        .addComponent(jLabel20)
                        .addComponent(jLabel26)
                        .addComponent(jLabel27)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSexo)
                        .addComponent(lblLastVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNasc))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados do Paciente", jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("CT");

        jLabel22.setText("CP");

        jLabel23.setText("LF");

        jLabel24.setText("CS");

        jLabel25.setText("PA");

        txtCT.setColumns(20);
        txtCT.setLineWrap(true);
        txtCT.setRows(4);
        txtCT.setTabSize(3);
        txtCT.setToolTipText("");
        txtCT.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtCT);

        txtCP.setColumns(20);
        txtCP.setLineWrap(true);
        txtCP.setRows(4);
        txtCP.setTabSize(3);
        txtCP.setToolTipText("");
        txtCP.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtCP);

        txtLF.setColumns(20);
        txtLF.setLineWrap(true);
        txtLF.setRows(4);
        txtLF.setTabSize(3);
        txtLF.setToolTipText("");
        txtLF.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtLF);

        txtCS.setColumns(20);
        txtCS.setLineWrap(true);
        txtCS.setRows(4);
        txtCS.setTabSize(3);
        txtCS.setToolTipText("");
        txtCS.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtCS);

        txtPA.setColumns(20);
        txtPA.setLineWrap(true);
        txtPA.setRows(4);
        txtPA.setTabSize(3);
        txtPA.setToolTipText("");
        txtPA.setWrapStyleWord(true);
        jScrollPane6.setViewportView(txtPA);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(63, 63, 63)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(61, 61, 61)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6))
                .addGap(26, 26, 26))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel31.setText("USG");

        jLabel32.setText("RX");

        jLabel33.setText("MGF");

        jLabel34.setText("DO");

        txtUSG.setColumns(20);
        txtUSG.setLineWrap(true);
        txtUSG.setRows(3);
        txtUSG.setTabSize(3);
        txtUSG.setToolTipText("");
        txtUSG.setWrapStyleWord(true);
        jScrollPane7.setViewportView(txtUSG);

        txtRX.setColumns(20);
        txtRX.setLineWrap(true);
        txtRX.setRows(3);
        txtRX.setTabSize(3);
        txtRX.setToolTipText("");
        txtRX.setWrapStyleWord(true);
        jScrollPane8.setViewportView(txtRX);

        txtMGF.setColumns(20);
        txtMGF.setLineWrap(true);
        txtMGF.setRows(3);
        txtMGF.setTabSize(3);
        txtMGF.setToolTipText("");
        txtMGF.setWrapStyleWord(true);
        jScrollPane9.setViewportView(txtMGF);

        txtDO.setColumns(20);
        txtDO.setLineWrap(true);
        txtDO.setRows(3);
        txtDO.setTabSize(3);
        txtDO.setToolTipText("");
        txtDO.setWrapStyleWord(true);
        jScrollPane10.setViewportView(txtDO);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9)
                    .addComponent(jScrollPane10))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jScrollPane7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jScrollPane10))
                .addGap(88, 88, 88))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))))
        );

        jTabbedPane1.addTab("Dados da Consulta", jPanel2);

        jLabel35.setText("Observações pertinentes");

        txtOutrasObs.setColumns(20);
        txtOutrasObs.setLineWrap(true);
        txtOutrasObs.setRows(5);
        txtOutrasObs.setWrapStyleWord(true);
        jScrollPane11.setViewportView(txtOutrasObs);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Outras Observações", jPanel8);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opções", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/novoUser.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Cadastra novo Paciente");
        btnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/DeleteUser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Exclui o paciente selecionado");
        btnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnListagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/Vista (215).png"))); // NOI18N
        btnListagem.setText("Listagem");
        btnListagem.setToolTipText("Lista todos os pacientes cadastrados");
        btnListagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnListagem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListagemActionPerformed(evt);
            }
        });

        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/sair.png"))); // NOI18N
        btnFechar.setText("Sair");
        btnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Lista todos os pacientes cadastrados");
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExcluir, btnListagem, btnNovo, btnSalvar});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnListagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExcluir, btnListagem, btnNovo, btnSalvar});

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtPesquisa.setToolTipText("Digite matrícula, cpf ou nome do paciente para procurar.");
        txtPesquisa.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medico/imagens/Localizar.png"))); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.setEnabled(false);
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Busca por ( CPF / Matrícula / Nome )");

        lblMsg.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        if (txtPesquisa.getText().isEmpty()) {
            btnPesquisa.setEnabled(false);
        } else {
            btnPesquisa.setEnabled(true);
        }
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        System.out.println("Procurar paciente: " + txtPesquisa.getText());
        // Verifica se ta o camp pesquisa ta vazio ...
        if (!txtPesquisa.getText().isEmpty()) {

            // Verifica se digitado e somante numero
            if (Utils.soNumero(txtPesquisa.getText())) {
                System.out.println("Somente numeros");

                // Se for digitado 11 digitos procura por CPF
                if (txtPesquisa.getText().length() == 11) {
                    System.out.println("Buscando por CPF");

                    PacienteDao pac = new PacienteDao();

                    List<Paciente> lista = pac.ListarPaciente(txtPesquisa.getText(), "Cpf");
                    if (lista.size() == 1) {
                        preencheCampos(lista);
                    } else if (lista.size() > 1) {
                        System.out.println("Encontrei mais de um paciente com este cpf abrindo janela de selecao");
                        if (frb == null) {
                            frb = new FrmResultBusca();
                            frb.setLocationRelativeTo(this);
                            frb.setVisible(true);
                        } else {
                            frb.setLocationRelativeTo(this);
                            frb.setVisible(true);
                        }
                        frb.recebePacientes(this, lista);
                    } else {
                        lblMsg.setText("Nenhum paciente encontrado!");
                    }
                    System.out.println("Tamanho da lista: " + lista.size());

                } else {
                    // Se for digitado outro numero procura por Matricula
                    System.out.println("Buscando por Matricula");

                    PacienteDao pac = new PacienteDao();

                    List<Paciente> lista = pac.ListarPaciente(txtPesquisa.getText(), "Matricula");
                    if (lista.size() == 1) {
                        preencheCampos(lista);
                        lblMsg.setText(null);
                    } else if (lista.size() > 1) {
                        System.out.println("Encontrado mais de uma matricula abriando janela de selecao");
                        if (frb == null) {
                            frb = new FrmResultBusca();
                            frb.setLocationRelativeTo(this);
                            frb.setVisible(true);
                        } else {
                            frb.setLocationRelativeTo(this);
                            frb.setVisible(true);
                        }
                        frb.recebePacientes(this, lista);
                        lblMsg.setText(null);
                    } else if (lista.size() <= 0) {
                        lblMsg.setText("Nenhum paciente encontrado!");
                        LimparCampos();
                        System.out.println("nenhuma paciente encontrado");
                    }
                    System.out.println("Tamanho da lista: " + lista.size());
                }
            } else {
                // Caso seja digitado nome ou parte do nome realiza busca por nome do paciente
                System.out.println("Buscando por nome: " + txtPesquisa.getText());

                PacienteDao pac = new PacienteDao();

                List<Paciente> lista = pac.ListarPaciente(txtPesquisa.getText(), "Nome");

                if (lista.size() == 1) {
                    preencheCampos(lista);
                    lblMsg.setText(null);
                } else if (lista.size() > 1) {

                    System.out.println("Encontrado mais de uma paciente abrindo janela de selecao");

                    if (frb == null) {
                        frb = new FrmResultBusca();
                        frb.setLocationRelativeTo(this);
                        frb.setVisible(true);
                    } else {
                        frb.setLocationRelativeTo(this);
                        frb.setVisible(true);
                    }
                    frb.recebePacientes(this, lista);
                } else {

                    System.out.println("Nenhum paciente encontrado!");
                    lblMsg.setText("Nenhum paciente encontrado!");
                    LimparCampos();
                }
                System.out.println("Tamanho da lista: " + lista.size());
            }
        }

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnPesquisaActionPerformed(null);
        }

        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            txtPesquisa.setText("");
            btnPesquisa.setEnabled(false);
        }
    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        guis.setiPac(null);
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void txtNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNascFocusLost
        if (!txtNasc.getText().equals("  /  /    ") || txtNasc.getText().length() != 10) {
            Integer idade;
            try {
                idade = Utils.getIdate(txtNasc.getText());
                lblIdade.setText(idade.toString());
            } catch (ParseException ex) {
                Logger.getLogger(FrmPacientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txtNascFocusLost

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        LimparCampos();
        txtNome.requestFocus();
        NovoPaciente = true;
        PacSelecionado = null;
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.setEnabled(false);

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ATENÇÃO - Campo [ NOME DO PACIENTE ] Não pode ser vazio.", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
            txtNome.requestFocus();
        } else {

            Paciente pac = new Paciente();

            if (PacSelecionado != null) {
                pac.setId(Long.parseLong(txtMat.getText()));
            }
            if (!txtMatCli.getText().equals("")) {
                pac.setMat(Long.parseLong(txtMatCli.getText()));
            }

            pac.setNome(txtNome.getText());
            pac.setCpf(txtCpf.getText());
            pac.setRg(txtRg.getText());
            pac.setDeclara(cmbDeclara.getSelectedItem().toString());
            pac.setSexo(cmbSexo.getSelectedItem().toString());
            pac.setNasc(txtNasc.getText());
            if (!txtCep.getText().equals("     -   ")) {
                String cep = txtCep.getText();
                String cepReplace = cep.replace("-", "");
                pac.setCep(Integer.parseInt(cepReplace));
            }
            pac.setEnd(txtEnd.getText());
            pac.setComp(txtComp.getText());
            pac.setCidade(txtCidade.getText());
            pac.setBairro(txtBairro.getText());
            pac.setUf(txtUf.getText());
            pac.setTelres(txtTelRes.getText());
            pac.setTelcom(txtTelCom.getText());
            pac.setTelcel(txtTelCel.getText());
            pac.setOp1(txtOp1.getText());
            pac.setTelfax(txtTelFax.getText());
            pac.setOp2(txtOp2.getText());
            pac.setTeloutro(txtTelOutro.getText());
            pac.setEmail(txtEmail.getText());
            pac.setObs(txtObs.getText());
            if (PacSelecionado == null) {
                pac.setDtcadastro(DataAtual());
            }
            pac.setDtupdate(DataAtual());
            pac.setCt(txtCT.getText());
            pac.setCp(txtCP.getText());
            pac.setLf(txtLF.getText());
            pac.setCs(txtCS.getText());
            pac.setPa(txtPA.getText());
            pac.setUsg(txtUSG.getText());
            pac.setRx(txtRX.getText());
            pac.setMgf(txtMGF.getText());
            pac.setTxtdo(txtDO.getText());
            pac.setOutrotxt(txtOutrasObs.getText());

            PacienteDao pacDao = new PacienteDao();

            if (PacSelecionado == null) {
                int lastID = pacDao.AdicionarPaciente(pac);

                if (lastID >= 1) {
                    lblMsg.setText("Paciente gravado com sucesso!");
                    txtMat.setText(String.valueOf(lastID));
                } else {
                    lblMsg.setForeground(Color.red);
                    lblMsg.setText("Erro ao gravar Paciente!");
                    txtNome.requestFocus();
                }
            } else {
                if (pacDao.AlterarPaciente(pac) == 1) {
                    lblMsg.setText("Paciente gravado com sucesso!");
                } else {
                    lblMsg.setForeground(Color.red);
                    lblMsg.setText("Erro ao gravar Paciente!");
                    txtNome.requestFocus();
                }
            }
        }

        this.setEnabled(true);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (this.PacSelecionado != null) {
            if (JOptionPane.showConfirmDialog(this, "Deseja realmente excluir paciente " + PacSelecionado.getNome() + " do sistema?", "Excluir Paciente", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                System.out.println("Excluindo paciente " + txtNome.getText());

                PacienteDao pacienteDao = new PacienteDao();

                if (pacienteDao.ExcluirPaciente(PacSelecionado) == 1) {
                    lblMsg.setText("Paciente " + PacSelecionado.getNome() + " excluido com sucesso!");
                    PacSelecionado = null;
                    LimparCampos();
                } else {
                    lblMsg.setText("Erro ao tentar excluir paciente " + PacSelecionado.getNome());
                }

            }
        } else {
            lblMsg.setText("Nenhum paciente selecionado para excluir.");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemActionPerformed
        System.out.println("Buscando Listagem: " + txtPesquisa.getText());

        PacienteDao pac = new PacienteDao();

        List<Paciente> lista = pac.ListarPaciente("Listagem", "Todos");

        if (lista.size() >= 1) {
            if (flist == null) {
                flist = new FrmListagem();
                flist.setLocationRelativeTo(this);
                flist.setVisible(true);
            } else {
                flist.setLocationRelativeTo(this);
                flist.setVisible(true);                
            }
            flist.recebePacientes(this, lista);
        } else {
            System.out.println("Nao encontrei nenhum paciente");
            lblMsg.setText("Não há paciente na base de dados!");
        }
    }//GEN-LAST:event_btnListagemActionPerformed

    private void txtNascKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNascKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtNasc.getText().length() == 10) {
                txtNascFocusLost(null);
            }
        }
    }//GEN-LAST:event_txtNascKeyPressed

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        if (!txtCpf.getText().equals("   .   .   -  ")) {
            PacienteDao pac = new PacienteDao();

            if (!validaCpf(txtCpf.getText())) {
                System.out.println("CPF Incorreto");
                lblErrorCpf.setText("CPF Inválido");
                txtCpf.requestFocus();
            } else {
                if (pac.verificaCpf(txtCpf.getText())) {
                    System.out.println("CPF ja existe");
                    JOptionPane.showMessageDialog(this, "CPF Já cadastrado para outro paciente!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
                    txtCpf.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_txtCpfFocusLost

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCpfKeyReleased
        lblErrorCpf.setText(null);
    }//GEN-LAST:event_txtCpfKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnListagem;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbDeclara;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblErrorCpf;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblLastVisita;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lbldtCadastro;
    private clinica.util.JTextUpper txtBairro;
    private javax.swing.JTextArea txtCP;
    private javax.swing.JTextArea txtCS;
    private javax.swing.JTextArea txtCT;
    private javax.swing.JFormattedTextField txtCep;
    private clinica.util.JTextUpper txtCidade;
    private clinica.util.JTextUpper txtComp;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JTextArea txtDO;
    private clinica.util.JTextUpper txtEmail;
    private clinica.util.JTextUpper txtEnd;
    private javax.swing.JTextArea txtLF;
    private javax.swing.JTextArea txtMGF;
    private clinica.util.JTextUpper txtMat;
    private clinica.util.JTextUpper txtMatCli;
    private javax.swing.JFormattedTextField txtNasc;
    private clinica.util.JTextUpper txtNome;
    private javax.swing.JTextArea txtObs;
    private clinica.util.JTextUpper txtOp1;
    private clinica.util.JTextUpper txtOp2;
    private javax.swing.JTextArea txtOutrasObs;
    private javax.swing.JTextArea txtPA;
    private clinica.util.JTextUpper txtPesquisa;
    private javax.swing.JTextArea txtRX;
    private clinica.util.JTextUpper txtRg;
    private clinica.util.JTextUpper txtTelCel;
    private clinica.util.JTextUpper txtTelCom;
    private clinica.util.JTextUpper txtTelFax;
    private clinica.util.JTextUpper txtTelOutro;
    private clinica.util.JTextUpper txtTelRes;
    private javax.swing.JTextArea txtUSG;
    private clinica.util.JTextUpper txtUf;
    // End of variables declaration//GEN-END:variables

    private void preencheCampos(List<Paciente> pac) {
        // Preenche campos com dados do paciente
        txtMat.setText(String.valueOf(pac.get(0).getId()));
        if (pac.get(0).getMat() != null) {
            txtMatCli.setText(String.valueOf(pac.get(0).getMat()));
        }
        txtNome.setText(pac.get(0).getNome());
        txtCpf.setText(pac.get(0).getCpf());
        txtRg.setText(pac.get(0).getRg());
        cmbDeclara.setSelectedItem(pac.get(0).getDeclara());
        cmbSexo.setSelectedItem(pac.get(0).getSexo());
        txtNasc.setText(pac.get(0).getNasc());
        txtEnd.setText(pac.get(0).getEnd());
        txtComp.setText(pac.get(0).getComp());
        txtBairro.setText(pac.get(0).getBairro());
        txtCidade.setText(pac.get(0).getCidade());
        txtUf.setText(pac.get(0).getUf());
        txtCep.setText(String.valueOf(pac.get(0).getCep()));
        txtTelRes.setText(pac.get(0).getTelres());
        txtTelCom.setText(pac.get(0).getTelcom());
        txtTelCel.setText(pac.get(0).getTelcel());
        txtOp1.setText(pac.get(0).getOp1());
        txtTelFax.setText(pac.get(0).getTelfax());
        txtOp2.setText(pac.get(0).getOp2());
        txtTelOutro.setText(pac.get(0).getTeloutro());
        txtEmail.setText(pac.get(0).getEmail());
        txtObs.setText(pac.get(0).getObs());
        lbldtCadastro.setText(pac.get(0).getDtcadastro());
        lblLastVisita.setText(pac.get(0).getDtupdate());
        txtCT.setText(pac.get(0).getCt());
        txtCP.setText(pac.get(0).getCp());
        txtLF.setText(pac.get(0).getLf());
        txtCS.setText(pac.get(0).getCs());
        txtPA.setText(pac.get(0).getPa());
        txtUSG.setText(pac.get(0).getUsg());
        txtRX.setText(pac.get(0).getRx());
        txtMGF.setText(pac.get(0).getMgf());
        txtDO.setText(pac.get(0).getTxtdo());
        txtOutrasObs.setText(pac.get(0).getOutrotxt());

        // Forca o campo texto a calcular a idade do paciente
        txtNascFocusLost(null);

        NovoPaciente = false;

        this.PacSelecionado = pac.get(0);
    }

    void recebeSelecionado(Paciente pac) {
        List<Paciente> lista = new ArrayList<>();

        lista.add(pac);
        preencheCampos(lista);

        this.PacSelecionado = pac;
    }

    private void LimparCampos() {
        txtPesquisa.setText(null);
        txtMat.setText(null);
        txtMatCli.setText(null);
        txtNome.setText(null);
        txtCpf.setText(null);
        txtRg.setText(null);
        cmbDeclara.setSelectedIndex(0);
        cmbSexo.setSelectedIndex(0);
        txtNasc.setText(null);
        lblIdade.setText(null);
        txtEmail.setText(null);
        txtMat.setText(null);
        txtCep.setText(null);
        txtEnd.setText(null);
        txtComp.setText(null);
        txtBairro.setText(null);
        txtCidade.setText(null);
        txtUf.setText(null);
        txtObs.setText(null);
        txtTelRes.setText(null);
        txtTelCom.setText(null);
        txtTelCel.setText(null);
        txtOp1.setText(null);
        txtTelFax.setText(null);
        txtOp2.setText(null);
        txtTelOutro.setText(null);
        lblLastVisita.setText(null);

        txtCT.setText(null);
        txtCP.setText(null);
        txtLF.setText(null);
        txtCS.setText(null);
        txtPA.setText(null);
        txtUSG.setText(null);
        txtRX.setText(null);
        txtMGF.setText(null);
        txtDO.setText(null);
        txtOutrasObs.setText(null);
    }

    private String DataAtual() {
        Date hoje = new Date(System.currentTimeMillis());
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        return formato.format(hoje);
    }

}
